# Generated by Django 5.2.8 on 2025-11-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название курса"),
                ),
                ("description", models.TextField(verbose_name="Подробное описание")),
                (
                    "short_description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Краткий питч"
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="courses/previews/",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Начальный"),
                            ("intermediate", "Средний"),
                            ("advanced", "Продвинутый"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="Уровень сложности",
                    ),
                ),
                (
                    "duration_hours",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Продолжительность (часы)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(default=False, verbose_name="Бесплатный курс"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликован"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название урока"),
                ),
                ("content", models.TextField(verbose_name="Контент")),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="Видео"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Продолжительность (мин)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликован"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
