# Generated by Django 5.2.8 on 2025-12-08 18:02

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Контент'),
        ),
    ]
